// Données des localisations regroupées par régions
export const locationsData = [
    {
      id: "ile-de-france",
      name: "Île-de-France",
      center: { lat: 48.8566, lng: 2.3522 },
      zoom: 8,
      locations: [
        {
          id: "paris-1",
          name: "Siège Social Paris",
          position: { lat: 48.8584, lng: 2.2945 },
          address: "16 Avenue de la Grande Armée, 75017 Paris",
          description: "Notre siège social situé au cœur de Paris, à proximité de l'Arc de Triomphe.",
          phone: "+33 1 45 67 89 10",
          email: "contact@entreprise.fr",
          website: "https://www.entreprise.fr",
        },
        {
          id: "paris-2",
          name: "Bureau La Défense",
          position: { lat: 48.8918, lng: 2.2385 },
          address: "Tour First, 1 Place des Saisons, 92400 Courbevoie",
          description: "Nos bureaux dans le quartier d'affaires de La Défense.",
          phone: "+33 1 45 67 89 11",
          email: "defense@entreprise.fr",
        },
        {
          id: "versailles",
          name: "Centre R&D Versailles",
          position: { lat: 48.8044, lng: 2.1232 },
          address: "12 Avenue de Paris, 78000 Versailles",
          description: "Notre centre de recherche et développement.",
          phone: "+33 1 45 67 89 12",
          email: "rd@entreprise.fr",
        },
      ],
    },
    {
      id: "auvergne-rhone-alpes",
      name: "Auvergne-Rhône-Alpes",
      center: { lat: 45.7578, lng: 4.832 },
      zoom: 8,
      locations: [
        {
          id: "lyon",
          name: "Bureau Lyon",
          position: { lat: 45.764, lng: 4.8357 },
          address: "56 Rue de la République, 69002 Lyon",
          description: "Notre bureau principal pour la région Auvergne-Rhône-Alpes.",
          phone: "+33 4 72 41 23 45",
          email: "lyon@entreprise.fr",
        },
        {
          id: "grenoble",
          name: "Centre Technique Grenoble",
          position: { lat: 45.1885, lng: 5.7245 },
          address: "5 Place Victor Hugo, 38000 Grenoble",
          description: "Centre technique spécialisé dans les nouvelles technologies.",
          phone: "+33 4 76 51 23 45",
          email: "grenoble@entreprise.fr",
        },
        {
          id: "clermont",
          name: "Agence Clermont-Ferrand",
          position: { lat: 45.7772, lng: 3.087 },
          address: "34 Rue du 11 Novembre, 63000 Clermont-Ferrand",
          description: "Agence commerciale pour l'Auvergne.",
          phone: "+33 4 73 92 12 34",
          email: "clermont@entreprise.fr",
        },
      ],
    },
    {
      id: "paca",
      name: "Provence-Alpes-Côte d'Azur",
      center: { lat: 43.2965, lng: 5.3698 },
      zoom: 8,
      locations: [
        {
          id: "marseille",
          name: "Bureau Marseille",
          position: { lat: 43.2965, lng: 5.3698 },
          address: "123 La Canebière, 13001 Marseille",
          description: "Bureau principal pour la région PACA.",
          phone: "+33 4 91 13 89 20",
          email: "marseille@entreprise.fr",
        },
        {
          id: "nice",
          name: "Agence Nice",
          position: { lat: 43.7102, lng: 7.262 },
          address: "45 Promenade des Anglais, 06000 Nice",
          description: "Agence commerciale pour la Côte d'Azur.",
          phone: "+33 4 93 62 47 50",
          email: "nice@entreprise.fr",
        },
        {
          id: "sophia",
          name: "Centre Innovation Sophia Antipolis",
          position: { lat: 43.6162, lng: 7.0652 },
          address: "291 Rue Albert Caquot, 06560 Valbonne",
          description: "Centre d'innovation technologique.",
          phone: "+33 4 92 96 50 00",
          email: "sophia@entreprise.fr",
          website: "https://innovation.entreprise.fr",
        },
      ],
    },
    {
      id: "occitanie",
      name: "Occitanie",
      center: { lat: 43.6047, lng: 1.4442 },
      zoom: 8,
      locations: [
        {
          id: "toulouse",
          name: "Bureau Toulouse",
          position: { lat: 43.6047, lng: 1.4442 },
          address: "12 Place du Capitole, 31000 Toulouse",
          description: "Bureau principal pour la région Occitanie.",
          phone: "+33 5 61 22 33 44",
          email: "toulouse@entreprise.fr",
        },
        {
          id: "montpellier",
          name: "Agence Montpellier",
          position: { lat: 43.6108, lng: 3.8767 },
          address: "1 Place de la Comédie, 34000 Montpellier",
          description: "Agence commerciale pour le Languedoc.",
          phone: "+33 4 67 58 38 22",
          email: "montpellier@entreprise.fr",
        },
      ],
    },
    {
      id: "bretagne",
      name: "Bretagne",
      center: { lat: 48.1173, lng: -1.6778 },
      zoom: 8,
      locations: [
        {
          id: "rennes",
          name: "Bureau Rennes",
          position: { lat: 48.1173, lng: -1.6778 },
          address: "22 Rue de la Monnaie, 35000 Rennes",
          description: "Bureau principal pour la région Bretagne.",
          phone: "+33 2 99 79 23 45",
          email: "rennes@entreprise.fr",
        },
        {
          id: "brest",
          name: "Centre Maritime Brest",
          position: { lat: 48.3904, lng: -4.4861 },
          address: "30 Rue du Château, 29200 Brest",
          description: "Centre spécialisé dans les technologies maritimes.",
          phone: "+33 2 98 33 10 10",
          email: "brest@entreprise.fr",
        },
      ],
    },
  ]
  